language: rust
rust:
- nightly
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  cargo doc &&
  echo "<meta http-equiv=refresh content=0;url=`echo $TRAVIS_REPO_SLUG | cut -d '/' -f 2`/index.html>" > target/doc/index.html &&
  sudo pip install ghp-import &&
  ghp-import -n target/doc &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
env:
  global:
  - secure: jfzSHCk09/dFSLGrqH+vzaXNPLKyGofyLrTsSo6fqDPu1v/UV83K8JXGtu/bXSt4Ixo9iS0ZRysHu9NNH9UITQmLPiAvDtIqxNiN20W/on3fB+Acs+rS3q8I7w4ModXyHvZmk0TZUUILzyBIFvgK8I8Zf3txBFd1WPl/+eAYMmjGL8znWJ46CPVNG3U5emI6WefZoigLb24IFzZQQApo9KHxaxAc8PwFSspTfcSkqhc93paMEE2guDAwvH3UBkwfX3SrTI6f2XvmjBZgs3Vq1HyDKrjrMVdBh0eSIApTooF1TeRBy7p5ltvCnmtQaEZvjja2SOM7nKDwHc/6/iVriVgHUteHPUsrIBxTaMniNRVtrQ/PffMZKxuVj9kOr6/gGSEPbnKJdTrfDoPCOFXAOoN3+S0ipmoOGCYc2Blr/SizlU2j6CTVP9tJ1roFen3k8lWHI2JJj9TF8UYIWqS4NxufISY/PA6xhTAvC7+RJqMYDnybTmbHYAwRPDkjYtB0u3rC0WLnr6e52nxNBEIOzARBDs0bRpHNep+ISgw0WUPRN5SXDOpoQL/9u/ZZlsKakZE85MOfED7k3aksShfIUVfjAimJlpg/vdW3EFbpfiMRepwKJ2TJ5iYWBzfAZbnF8eP+yDUB1cWYc0Y0XqzkfsO2dlopKxb8WrvD0Vt7RLY=
