language: rust
rust:
- nightly
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  cargo doc &&
  echo "<meta http-equiv=refresh content=0;url=`echo $TRAVIS_REPO_SLUG | cut -d '/' -f 2`/index.html>" > target/doc/index.html &&
  sudo pip install ghp-import &&
  ghp-import -n target/doc &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
env:
  global:
    secure: Bs3RBDmaSBLRdhyYUiydehKxNzfGqc/uWcsjLXF+relb0S5DFOHmFud5XTEp+mUIyK2Ud9SWB171FHpLwrJvFCylqdtljrKZVYJCiy50D4bB5u6/rYce5SFv+xlUIRbd1uxqQcmskYmcu8cV3CSNphimsBPHXjYgd17SZjVwckdbCVDM0QEgCfkRVYlnkbr/jrCxBz+bq/wLFWA0QfE2HByb58II0eR4ZY/TQlfxXwQfTawsg5NPb4nksQfDCG8OLWkMc7Q10DV5WMSjT52r7Iv3hOw6uZkPtJMAlOt8Ufw1EWWjVoyo5EAema4ALDe7CuSy3jzijLQZvaecfT7HV1ppARz8h7ymnka5q7BtRCqIDa2iYbWPjp8cepxcbz9VJN+RLkDhIf5usy1JbXfIjdkqfBSfqQIJ3aBX1efpnjmyxv72F5ed8itFxmZY9yU3FJgzZBmnVWInSuecBxf6cq3NTSTRB8+uIrdXV7krcZMgv66vJhFwhcMDLJxc/jfKoZ5ctr3yrzs3nkLoXSBxgDeQ9rMZuK87eftGDjQAchgHBtoEzyaBtTZICIz/eqT22sxR9DLO1k4vVJdsmTdorlTF7SXpjyvtc1bIKjED64KFdZrV0cNei0SGW54W+22Bqoj53h5riN8HZcCDOoRn1B89JQuATfZwX0+LIlpxddg=
